#!/bin/bash
# Taken from the default emacsclient.desktop, it was easier to modify this as
# a standalone script than leaving it embedded with escapes.

if [ -n "$*" ]
then
    emacsclient-new-tab "$@"
else
    emacsclient-new-window
fi
