# TODO: Split interactive stuff into a separate file

# Detect when we're running in Windows under a Unix-like shell
# todo: git bash?
if [ ! -z "$WSL_DISTRO_NAME" ]; then
    export WINDOWS=WSL
elif [ "$OSTYPE" == cygwin ]; then
    export WINDOWS=Cygwin
elif [ "$OSTYPE" == msys ]; then
    export WINDOWS=MSYS
fi

# Assume there's an X server running if we're on Windows
if [ -n "$WINDOWS" ] && [ -z "$DISPLAY" ]; then
    export DISPLAY=0:0
fi

# Report the user, hostname, and terse machine info when opening a new
# interactive shell
if [[ $- == *i* ]]; then
    # These should always exist if our shell is actually bash
    DISTRO="$OSTYPE $HOSTTYPE"
    if command -v lsb_release &> /dev/null; then
        DISTRO=$(lsb_release -sd)
    elif command -v uname &> /dev/null; then
        DISTRO=$(uname -sr)
    fi
    SEP="\e[90m│\e[0m"
    echo -e "$SEP \e[32m$USER @ $(hostname) $SEP \e[37m$DISTRO${WINDOWS:+ $WINDOWS}\e[0m $SEP"
fi

# The first part of this file runs both interactively and non-interactively
# =========================================================================
unset -f command_not_found_handle
export HISTCONTROL=ignoreboth:erasedups

if [ ! -z "$WSL_DISTRO_NAME" ] \
    || [ "$OSTYPE" == cygwin ] \
    || [ "$OSTYPE" == msys ]; then
    export WINDOWS=1
    # Assume there's an X server running
    if [ -z "$DISPLAY" ]; then
        export DISPLAY=0:0
    fi
fi

# Fix ugly dircolors, the default blue on green is impossible to read.
export LS_COLORS+=':ow=01;92;100'
export EDITOR=vi
export VISUAL=vi
export PAGER='less -R'
export SCREENDIR="$HOME/.screen"
[ ! -d "$SCREENDIR" ] && mkdir "$SCREENDIR" && chmod 700 "$SCREENDIR"

# The rest of this file is skipped if not running interactively
# =============================================================
case $- in
    *i*) ;; # Interactive session
    *) return ;; # Non interactive
esac

# Ignore legacy scroll lock on <C-S> and <C-Q>
stty -ixon

alias rgrep='grep -Iirn'
alias more='less'
alias gdb='gdb -q'
alias preview='feh --scale -d . &'

# Pipe into this to prevent really long lines from taking over shell output.
alias trunc="cut -b 1-120"

# View terminal escape sequences for keystrokes
alias keys='echo "Ctrl-D on a new line to end input" ; od -t x1 -t u1'

# I never remember xxd
alias hex='xxd -g 1'

if [[ $OSTYPE == *darwin* ]]; then
    alias ls='ls -F'
    export BASH_SILENCE_DEPRECATION_WARNING=1
elif [ -z "$WINDOWS" ]; then
    alias ls="ls -p -N --color=auto -I '*System Volume Information*' -I '*RECYCLE.BIN*' -I lost+found"
else
    alias ls="ls -F --color=auto"
fi

alias tmux='tmux -u'
alias usermount="udisksctl"

# NOTE: Takes the repo name before any flags. Extracting the last argument
# was a lot more of a headache than just swapping the order.
ghclone() {
    REPO="$1"; shift
    git clone "https://github.com/$REPO" "$@"
}

# View the history of a specific file in a repo, including renames
githist() {
    GIT_FILENAME="$1"; shift
    git log --follow -p -U1 --oneline "$@" -- "${GIT_FILENAME}"
}

# View the history of the given function in the given filename
gitfn() {
    GIT_FUNCNAME="$1"; shift
    GIT_FILENAME="$1"; shift
    git log -U1 -L --oneline ":${GIT_FUNCNAME}:${GIT_FILENAME}" "$@"
}

is_executable () {
    command -v "$@" &> /dev/null
}

# Allow launching emacsclient directly without having to start a daemon first
if is_executable emacsclient; then
    alias emc='emacsclient-wrapper'
    # alias em='emacsclient --alternate-editor="" --tty'
    alias em='emacs -nw'
fi

# These scripts are in my dotfiles.
# They pick an appropriate editor based on what's installed.
export EDITOR=edit-tty
export VISUAL=edit

# The colon at the end indicates to prepend to the existing manpath
export MANPATH="$HOME/.local/share/man:"

# apt installs bat as batcat, make a symlink so that it can be used as bat
if is_executable batcat && ! is_executable bat; then
    ln -s "$(which batcat)" "$HOME/.local/bin/bat"
fi

# Use bat as a cat replacement
if is_executable bat; then
    bathelp() {
        bat --plain --language=help
    }
    help() {
      "$@" --help 2>&1 | bathelp
    }
    alias cat='bat' # bat says it's smart enough to not break this
fi

is_executable batman && eval "$(batman --export-env)"

if is_executable fdfind && ! is_executable fd; then
    ln -s "$(which fdfind)" "$HOME/.local/bin/fd"
fi

if is_executable glow; then
    alias glow='glow --mouse --pager'
    # I'll probably type "md" to try and find a Markdown viewer
    alias mdv=glow
fi

is_executable rlwrap && is_executable sbcl && alias sbcl='rlwrap sbcl'

TITLE="\[\e]0;\w\a\]"
DARK="\[\e[90m\]"
LIGHT="\[\e[37m\]"
DIM="\[\e[2m\]"
RESET="\[\e[0m\]"
export PS1="$TITLE$DARK\w$LIGHT$DIM $ $RESET"

