#!/bin/bash

CMD=vi
if command -v emacsclient &> /dev/null
then
    CMD=emacsclient-wrapper
elif command -v nvim &> /dev/null
then
    CMD=nvim
elif command -v vim &> /dev/null
then
    CMD=vim
fi

exec $CMD "$@"
