#!/bin/bash

# Handle multiple arguments. Assume all of them are file names, since this
# will usually be called by the desktop environment.
for fname in "$@"
do
    # Note that find-file-new-tab is a custom function in post-init.el
    emacsclient --no-wait --alternate-editor="" --reuse-frame --eval "(find-file-new-tab \"$fname\")"
done
