#!/bin/bash

VENV_HOME="$HOME/.venv"

# There has to be a better way
if command -v python3.10 &> /dev/null; then
    PYTHON3="$(which python3.10)"
elif command -v python3.9 &> /dev/null; then
    PYTHON3="$(which python3.9)"
elif command -v python3.8 &> /dev/null; then
    PYTHON3="$(which python3.8)"
elif command -v python3 &> /dev/null; then
    PYTHON3="$(which python3)"
elif command -v python &> /dev/null; then
    PYTHON3="$(which python)"
else
    exit 1
fi

__venv_repo() {
    basename "$(git rev-parse --show-toplevel 2> /dev/null)"
}

__venv_setup() {
    mkdir -p "$VENV_HOME"
}

venv() {
    __venv_setup
    if [ "$#" -lt 1 ]; then
        ls -1a "$VENV_HOME" | sed '1,2d'
        return
    fi
    # cygwin and msys have a different path, but not WSL
    if [ -z "$WINDOWS" -o ! -z "$WSL_DISTRO_NAME" ]; then
        ACTIVATE="$VENV_HOME/$1/bin/activate"
    else
        ACTIVATE="$VENV_HOME/$1/Scripts/activate"
    fi
    if [ ! -d "$VENV_HOME/$1" -o ! -f "$ACTIVATE" ]; then
        echo "creating venv in '$VENV_HOME/$1'"
        $PYTHON3 -m venv "$VENV_HOME/$1"
        source "$ACTIVATE"
        $PYTHON3 -m pip install --upgrade pip
    else
        source "$ACTIVATE"
    fi
}

activate () {
    if command -v deactivate &> /dev/null; then
        deactivate
    fi
    if git branch &> /dev/null; then
        venv "$(__venv_repo)"
    else
        echo "No project found, are you sure you are in a git repo?"
    fi
}
