(setq package-enable-at-startup nil)
(setq byte-compile-warnings '(not obsolete docstrings lexical free-vars noruntime))
(setq gc-cons-threshold 10000000)
(setq read-process-output-max (* 1024 1024))
(add-to-list 'default-frame-alist '(cursor-type . bar))
(add-to-list 'default-frame-alist '(vertical-scroll-bars . nil))
(add-to-list 'default-frame-alist '(horizontal-scroll-bars . nil))
(setq frame-resize-pixelwise t)
