(setq package-enable-at-startup nil)
(setq byte-compile-warnings '(not obsolete docstrings lexical free-vars noruntime))
(setq gc-cons-threshold 10000000)
(setq read-process-output-max (* 1024 1024))
(setq default-frame-alist
      '((vertical-scroll-bars . nil)
        (horizontal-scroll-bars . nil)
        (cursor-type . bar)
        (width . 180)
        (height . 60)))
(setq initial-frame-alist (mapcar #'identity default-frame-alist))
(setq frame-resize-pixelwise t)
