(setopt native-comp-async-query-on-exit t)
(setopt native-comp-bootstrap-deny-list '("loaddefs\\.el\\.gz\\'"))
(setopt native-comp-jit-compilation-deny-list '("loaddefs\\.el\\.gz\\'"))
(setopt native-comp-async-report-warnings-errors 'silent)
(setq byte-compile-warnings '(not obsolete docstrings))
(setq gc-cons-threshold 10000000)
(setq read-process-output-max (* 1024 1024))
(setq inhibit-startup-message t)
(setq inhibit-startup-echo-area-message (user-login-name))
(set-foreground-color "#EEEEEE")
(set-background-color "#222228")
(setq frame-resize-pixelwise t)
(setq default-frame-alist '((cursor-type . bar)
                            (height . 35)
                            (width . 120)
                            (vertical-scroll-bars . nil)
                            (horizontal-scroll-bars . nil)
                            (left-fringe . 8)
                            (right-fringe . 8)))
