(deftheme mostly-mono
  "mono-ish theme for focusing")

(custom-theme-set-faces
 'mostly-mono
 '(cursor ((t (:background "#FFFFFF"))))
 '(fixed-pitch ((t (:slant normal :weight regular :height 130 :width normal :foundry "UKWN" :family "IosevkaTermSlab NFP"))))
 '(variable-pitch ((t (:slant normal :weight regular :height 120 :width normal :foundry "GOOG" :family "Roboto Condensed"))))
 '(escape-glyph ((t (:weight semi-bold))))
 '(homoglyph ((t nil)))
 '(minibuffer-prompt ((t (:background "black" :foreground "white" :weight bold))))
 '(highlight ((t (:background "#0A0D10" :box (:line-width (-1 . -1) :color "black")))))
 '(region ((t (:background "#555566"))))
 '(shadow ((t (:foreground "#4F4F5F"))))
 '(secondary-selection ((t (:inherit region :background "#23354F"))))
 '(trailing-whitespace ((t (:strike-through t :foreground "grey50"))))
 '(font-lock-bracket-face ((t (:inherit font-lock-punctuation-face))))
 ;; Seems to mostly be used for :properties
 '(font-lock-builtin-face ((t (:foreground "#AAAABB"))))
 '(font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
 ;; Alternate stand-out red comments
 ;; '(font-lock-comment-face ((t (:foreground "#DD7777" :height 0.95 :family "Iosevka Etoile Light"))))
 '(font-lock-comment-face ((t (:foreground "#7D7D8F" :height 0.95 :family "Iosevka Etoile"))))
 '(font-lock-constant-face ((t (:height 0.95 :family "Iosevka Etoile" :foreground "#ffccdd"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit font-lock-regexp-grouping-backslash))))
 '(font-lock-function-call-face ((t (:inherit default))))
 '(font-lock-function-name-face ((t (:foreground "#FFFFFF" :weight bold))))
 '(font-lock-keyword-face ((t (:family "M+ 1m" :weight medium))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-number-face ((t (:foreground "#FFDDDD"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#ABABBC"))))
 '(font-lock-property-name-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-property-use-face ((t (:inherit font-lock-property-name-face))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:inherit fixed-pitch :foreground "#DDCCCC" :weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:inherit font-lock-regexp-grouping-backslash))))
 '(font-lock-string-face ((t (:height 0.95 :family "Iosevka Etoile" :foreground "#CBBBBB"))))
 '(font-lock-type-face ((t (:foreground "#CCCCCC" :slant oblique :weight normal))))
 '(font-lock-variable-name-face ((t (:inherit fixed-pitch :foreground "#FFFFFF"))))
 '(font-lock-variable-use-face ((t (:inherit font-lock-variable-name-face))))
 '(font-lock-warning-face ((t (:background "#503A3D" :foreground "#F0BBBB"))))
 '(button ((t (:inherit link))))
 '(link ((t (:foreground "#AABBDD" :underline t :weight normal))))
 '(link-visited ((t (:underline t :foreground "#DDCCEE"))))
 '(fringe ((t (:inherit default))))
 '(header-line ((t (:inherit variable-pitch :background "#666677" :foreground "#DDDDDD" :box (:line-width (1 . 1) :color "black")))))
 '(tooltip ((t (:foreground "#DDDDF0" :background "#333333" :inherit variable-pitch))))
 '(mode-line ((t (:family "Roboto Condensed"
                          :foreground "#EEEEFF" :background "#884444" :underline (:color "#DD7777" :position 0)))))
 '(mode-line-buffer-id ((t (:weight medium))))
 '(mode-line-emphasis ((t (:weight bold :foreground "white"))))
 '(mode-line-highlight ((t (:background "#777788"))))
 '(mode-line-inactive ((t (:family "Roboto Condensed" :foreground "#444450" :background "#22222B" :box (:line-width (-1 . -1) :color "grey30")))))
 '(isearch ((t (:background "#5A5D60" :foreground "#FFFFFF"))))
 '(isearch-fail ((t (:weight bold :foreground "black" :background "#FFCCCC"))))
 '(lazy-highlight ((t (:foreground "#DDDDDD" :background "#3A3D40"))))
 '(match ((t (:background "#3A3D40" :foreground "#CAEEEE"))))
 '(next-error ((t (:height 1.1 :underline unspecified :foreground "white" :background "#9E3699"))))
 '(query-replace ((t (:inherit isearch))))
 '(widget-field ((t (:extend t :background "gray14" :foreground "#EEEEEE"))))
 '(italic ((t (:slant italic))))
 '(bold ((t (:weight bold))))
 '(show-paren-match ((t (:inverse-video t :box (:line-width (-2 . -2) :color "#2A2D30" :style flat-button)))))
 '(whitespace-tab ((t (:foreground "#667788"))))
 '(fixed-pitch-serif ((t (:inherit fixed-pitch))))
 '(window-divider-first-pixel ((t (:foreground "#1A1D20"))))
 '(window-divider-last-pixel ((t (:foreground "#1A1D20"))))
 '(tab-line ((t (:underline (:color "#4D4D5F" :style line :position 0) :height 0.9 :foreground "#8D8DAF" :background "#0A0D10" :inherit variable-pitch))))
 '(tab-line-tab ((t (:inherit tab-line-tab-current))))
 '(tab-line-tab-current ((t (:height 1.0 :underline (:color "#1A1D20" :style line :position 0) :box (:line-width (1 . 1) :color "#2D2D2F" :style flat-button) :foreground "#DDDDF0" :background "#1A1D20" :inherit tab-line-tab))))
 '(tab-line-tab-inactive ((t (:background "#2D2D38" :foreground "#8D8D98" :inherit tab-line-tab :underline (:color "#4D4D5F" :style line :position 0)))))
 '(tab-line-highlight ((t (:height 1.0 :inherit highlight))))
 '(orderless-match-face-0 ((t (:weight bold :foreground "#FFFFFF" :underline "#72A4FF"))))
 '(orderless-match-face-1 ((t (:weight bold :foreground "#FFFFFF" :underline "#ed92f8"))))
 '(orderless-match-face-2 ((t (:weight bold :foreground "#FFFFFF" :underline "#90d800"))))
 '(orderless-match-face-3 ((t (:weight bold :foreground "#FFFFFF" :underline "#f0ce43"))))
 '(hl-line ((t (:background "#333340" :extend t :underline (:color "black" :position 0)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#1A1D20" :foreground "#DDDDE8" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 130 :width normal :foundry "UKWN" :family "Iosevka NFP"))))
 '(eshell-prompt ((t (:foreground "#88BBDD" :weight medium))))
 )

(provide-theme 'mostly-mono)
