#!/bin/bash

if [ ! -d .git ]; then
    echo "This script must be ran from inside the repository directory. Exiting."
    exit 1
fi

# link SRC DST
function link {
    # Overwrite symlinks without prompting, otherwise make a backup
    local SRC="$PWD/$1"
    local DST="$HOME/$2"
    if [ -L "$DST" ]; then
        ln -n -f -s "$SRC" "$DST"
    elif [ ! -d "$DST" ]; then
        [ -f "$DST" ] && echo "$DST exists and is not a symlink, linking with backup"
        ln -n -b -s "$SRC" "$DST"
    else
        echo "$DST exists and is a directory, skipping"
    fi
}

link dot/bashrc     .bashrc
link dot/profile    .profile
link dot/tmux.conf  .tmux.conf
link dot/inputrc    .inputrc
link dot/gitignore  .gitignore
link dot/vimrc      .vimrc

mkdir -p $HOME/.config/nvim/autoload

link nvim/init.vim       .config/nvim/init.vim
link nvim/ginit.vim      .config/nvim/ginit.vim
link nvim/filetype.vim   .config/nvim/filetype.vim
link nvim/conf           .config/nvim/conf
link nvim/syntax         .config/nvim/syntax
link nvim/after          .config/nvim/after
link nvim/ftplugin       .config/nvim/ftplugin
link nvim/coc-settings.json .config/nvim/coc-settings.json

